"""
Tool implementations for the Travel AI Agent.
These tools are called by the Gemini agent to perform specific actions.
"""

import urllib.parse
from typing import Optional
from tavily_client import get_tavily_client








async def search_web(query: str) -> dict:
    """
    Search the web using Tavily for travel-related information.
    
    Args:
        query: Search query
        
    Returns:
        Search results with URLs and summaries
    """
    client = get_tavily_client()
    results = await client.search(query)
    return results


def generate_itinerary(destination: str, days: int, preferences: Optional[str] = None) -> dict:
    """
    Generate a base itinerary structure (actual content generated by Gemini).
    
    Args:
        destination: Travel destination
        days: Number of days
        preferences: Optional travel preferences
        
    Returns:
        Itinerary metadata and prompt for generation
    """
    return {
        "destination": destination,
        "days": days,
        "preferences": preferences or "balanced mix of culture, food, and relaxation",
        "generate_prompt": True,
        "message": f"📅 Generating a {days}-day itinerary for {destination}..."
    }


def recommend_destinations(
    budget: Optional[str] = None,
    style: Optional[str] = None,
    interests: Optional[list] = None,
    duration: Optional[str] = None,
    season: Optional[str] = None
) -> dict:
    """
    Structure preferences for destination recommendations.
    
    Args:
        budget: Budget range (e.g., "low", "medium", "luxury")
        style: Travel style (e.g., "adventure", "relaxation", "cultural")
        interests: List of interests
        duration: Trip duration
        season: Preferred travel season
        
    Returns:
        Structured preferences for recommendation generation
    """
    preferences = {
        "budget": budget or "flexible",
        "style": style or "balanced",
        "interests": interests or ["sightseeing", "local cuisine", "culture"],
        "duration": duration or "flexible",
        "season": season or "any"
    }
    
    return {
        "preferences": preferences,
        "generate_prompt": True,
        "message": "🗺️ Finding perfect destinations based on your preferences..."
    }


# Tool definitions for Gemini function calling
TOOL_DEFINITIONS = [
    {
        "name": "search_web",
        "description": "Search the web for travel information, booking websites, flight prices, hotel deals, and current travel news. Use this when users ask about booking, prices, or need real-time information.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The search query for travel-related information"
                }
            },
            "required": ["query"]
        }
    },

    {
        "name": "generate_itinerary",
        "description": "Generate a detailed day-by-day travel itinerary for a destination. Use this when users want to plan a trip or ask for itinerary suggestions.",
        "parameters": {
            "type": "object",
            "properties": {
                "destination": {
                    "type": "string",
                    "description": "The travel destination"
                },
                "days": {
                    "type": "integer",
                    "description": "Number of days for the trip"
                },
                "preferences": {
                    "type": "string",
                    "description": "Optional travel preferences or interests"
                }
            },
            "required": ["destination", "days"]
        }
    },
    {
        "name": "recommend_destinations",
        "description": "Recommend travel destinations based on user preferences. Use this when users describe what kind of trip they want.",
        "parameters": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "string",
                    "description": "Budget range: 'budget', 'moderate', 'luxury'"
                },
                "style": {
                    "type": "string",
                    "description": "Travel style: 'adventure', 'relaxation', 'cultural', 'romantic', 'family'"
                },
                "interests": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "List of interests like 'beaches', 'mountains', 'history', 'food'"
                },
                "duration": {
                    "type": "string",
                    "description": "Trip duration like '3 days', '1 week'"
                },
                "season": {
                    "type": "string",
                    "description": "Preferred travel season"
                }
            },
            "required": []
        }
    }
]
